name: "Build kernel."              # Description of the workflow.
on:
  push:
    branches: 12                                   # Branch to build.
  workflow_dispatch:                                  # Allow to manually trigger workflow.
jobs:
  build:
    name: "Build kernel"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout kernel source"     
      uses: actions/checkout@v3
    - name: "Android kernel build"                    
      uses: lemniskett/android-kernel-actions@master
      with:
        arch: arm64                                  
        compiler: aosp-clang/android13-release/clang-r450784d/binutils           
        defconfig: mi_defconfig
        image: Image.gz-dtb                           
    
    - name: Release build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Release 
        path: /home/runner/work/android_kernel_xiaomi_sdm845/android_kernel_xiaomi_sdm845/out/arch/arm64/boot/Image.gz-dtb
        if-no-files-found: warn
      
          
