name: "Build kernel."              # Description of the workflow.
on:
  push:
    branches: 12                                   # Branch to build.
  workflow_dispatch:                                  # Allow to manually trigger workflow.
jobs:
  build:
    name: "Build kernel"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout kernel source"     
      uses: actions/checkout@v2
    - name: "Android kernel build"                    
      uses: lemniskett/android-kernel-actions@master
      with:
        arch: arm64                                  
        compiler: clang/11/binutils           
        defconfig: mi_defconfig
        image: Image.gz-dtb                           
    
    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.<step id>.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
    
