name: "Build kernel."              # Description of the workflow.
on:
  push:
    branches: 12                                   # Branch to build.
  workflow_dispatch:                                  # Allow to manually trigger workflow.
jobs:
  build:
    name: "Build kernel"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout kernel source"                  # Clone the kernel source.
      uses: actions/checkout@v2
    - name: "Android kernel build"                    # Build kernel with lemniskett/android-kernel-actions.
      uses: lemniskett/android-kernel-actions@master
      with:
        arch: arm64                                   # Specify arch
        compiler: aosp-clang/master/clang-r450784d/binutils                               # Specify toolchain to use
        defconfig: mi_defconfig                   # Specify defconfig to use
        image: Image.gz-dtb                           # Specify final build file
    - name: releases-action
  # You may pin to the exact commit or the version.
  # uses: nickatnight/releases-action@893540eb446b37c82cf414f2bb439e805e70b41f
      uses: nickatnight/releases-action@v2
      with:
    # Name of branch to release from
        branch: 12 # optional, default is master
    # Name of the release
        name: test # optional
    # Message for the release
        message: hi # optional
    # Draft or naw?
        draft: true # optional, default is false
    # Pre-release or naw
        prerelease: false # optional, default is false
    # Name of tag
        tag: none # optional
    
